# Generated by Django 4.2.2 on 2023-12-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
